DROP TABLE completeNycJobs; 

CREATE TABLE completeNycJobs (
	index INT PRIMARY KEY NOT NULL,
	jobID int,
	agency varchar(255) NOT NULL,
	postingType varchar (255),
	numOfPositions INT,
	businessTitle varchar (255) NOT NULL,
	civilServiceTitle varchar(255),
	titleCodeNo varchar(255),
	level varchar(255),
	jobCategory varchar (750) NOT NULL,
	fullTimePartTime varchar (255),
	salaryRangeFrom float,
	salaryRangeTo float,
	salaryFrequency varchar(255),
	workLocation varchar(255),
	divisionWorkUnit varchar(255),
	jobDescripton varchar(255),
	minQualRequirements varchar(255),
	preferredSkills varchar(255),
	additionalInformation varchar(255),
	toApply varchar(255),
	hoursShift varchar(255),
	workLocation1 varchar (255),
	recruitmentContact float,
	residencyRequirement varchar(255),
	postingDate varchar(255),
	postUntil varchar(255),
	postingUpdated varchar(255),
	processDate varchar(255),
	newLat float,
	newLong float,
	formattedAddress varchar(255),
	zip float, 
	borough varchar(255)
	
);